"""
Algebraic computations on groups: subgroups, conjugacy classes, cosets,
center, subgroup lattice, Cayley edges, element orders.

All functions take a Group (with precomputed Cayley table) and return
JSON-serializable results. The Group is identified by its symbol string.
"""

from __future__ import annotations

from typing import Optional
from group import Group, GroupElement


# ── Performance Guards ──────────────────────────────────────────────────────

PERF_CUTOFF = 120  # Order above which we skip heavy computations


# ── Helpers ─────────────────────────────────────────────────────────────────

def _element_key(elements: list[GroupElement]) -> str:
    """Sorted comma-separated element IDs."""
    return ",".join(sorted(e.id for e in elements))


# ── Element Order ───────────────────────────────────────────────────────────

def compute_element_order(group: Group, element_id: str) -> Optional[dict]:
    """Compute the order of an element and return its cyclic subgroup cycle."""
    el = group.element_by_id(element_id)
    if el is None:
        return None

    visited: set[str] = set()
    cycle: list[GroupElement] = []
    current = el
    while current.id not in visited:
        visited.add(current.id)
        cycle.append(current)
        current = group.multiply(current, el)

    return {
        "element_id": el.id,
        "element_label": el.label,
        "order": len(cycle),
        "cycle": [
            {"id": e.id, "label": e.label, "value": e.value}
            for e in cycle
        ],
    }


# ── Cyclic Subgroups ────────────────────────────────────────────────────────

def _cyclic_subgroups(group: Group) -> list[set[str]]:
    """Generate all distinct cyclic subgroups of G."""
    seen: set[str] = set()
    subgroups: list[set[str]] = []

    for el in group.elements:
        # Generate <el>
        cyclic: set[str] = set()
        current = el
        while current.id not in cyclic:
            cyclic.add(current.id)
            current = group.multiply(current, el)

        key = _element_key([e for e in group.elements if e.id in cyclic])
        if key not in seen:
            seen.add(key)
            subgroups.append(cyclic)

    return subgroups


def _close_under_multiply(group: Group, seed_ids: list[str]) -> list[str]:
    """Compute <seed>, the subgroup generated by the seed elements."""
    result: list[str] = []
    result_set: set[str] = set()
    for sid in seed_ids:
        if sid not in result_set:
            result.append(sid)
            result_set.add(sid)

    changed = True
    while changed:
        changed = False
        k = len(result)
        for i in range(k):
            for j in range(i, k):
                idx_i = group._id_to_idx[result[i]]
                idx_j = group._id_to_idx[result[j]]
                prod_idx = group._table[idx_i][idx_j]
                prod_id = group.elements[prod_idx].id
                if prod_id not in result_set:
                    result.append(prod_id)
                    result_set.add(prod_id)
                    changed = True
    return result


def _is_normal_closure(group: Group, element_ids: set[str]) -> bool:
    """Check if a set of elements is closed under conjugation."""
    id_to_idx = group._id_to_idx
    elems = group.elements
    for hid in element_ids:
        h_idx = id_to_idx[hid]
        for g in elems:
            g_idx = id_to_idx[g.id]
            # conj = g * h * g^{-1}
            gh = group._table[g_idx][h_idx]
            ginv = group._inverse_map[g_idx]
            conj_idx = group._table[gh][ginv]
            conj_id = elems[conj_idx].id
            if conj_id not in element_ids:
                return False
    return True


# ── Subgroup Enumeration ────────────────────────────────────────────────────

def compute_subgroups(group: Group) -> dict:
    """Find all subgroups of G (including {e} and G)."""
    n = group.order

    if n > PERF_CUTOFF:
        return {"subgroups": [], "total_count": 0, "truncated": True}

    # Collect subgroups as sorted id tuples to deduplicate
    subgroup_sets: list[frozenset[str]] = []
    seen_keys: set[str] = set()

    def add_subgroup(ids: set[str]) -> bool:
        sorted_ids = sorted(ids)
        key = ",".join(sorted_ids)
        if key in seen_keys or len(ids) == 0 or len(ids) >= n:
            return False
        seen_keys.add(key)
        subgroup_sets.append(frozenset(sorted_ids))
        return True

    # Phase 1: Cyclic subgroups
    cyc = _cyclic_subgroups(group)
    for c_set in cyc:
        add_subgroup(c_set)

    # Phase 2: Pair-join closure
    while True:
        prev_count = len(subgroup_sets)
        for i in range(prev_count):
            for j in range(i + 1, prev_count):
                union = list(subgroup_sets[i] | subgroup_sets[j])
                closed = _close_under_multiply(group, union)
                add_subgroup(set(closed))
        if len(subgroup_sets) == prev_count:
            break

    # Phase 3: Add trivial subgroup {e} and full group G
    identity_id = group.elements[group.identity_idx].id
    all_id_set = frozenset(e.id for e in group.elements)

    # Build result
    all_sets = [frozenset([identity_id])] + subgroup_sets + [all_id_set]

    # Deduplicate and sort by size
    final_sets: list[frozenset[str]] = []
    final_keys: set[str] = set()
    for s in all_sets:
        key = ",".join(sorted(s))
        if key not in final_keys:
            final_keys.add(key)
            final_sets.append(s)
    final_sets.sort(key=lambda s: len(s))

    id_to_elem = {e.id: e for e in group.elements}
    subgroups = []
    for s in final_sets:
        elems = sorted((id_to_elem[eid] for eid in s), key=lambda e: e.id)
        is_normal = _is_normal_closure(group, s)
        subgroups.append({
            "elements": [{"id": e.id, "label": e.label, "value": e.value} for e in elems],
            "is_normal": is_normal,
            "order": len(elems),
        })

    return {"subgroups": subgroups, "total_count": len(subgroups)}


# ── Normal Subgroup Enumeration ─────────────────────────────────────────────

def compute_normal_subgroups(group: Group) -> dict:
    """Find all normal subgroups via conjugacy class union method."""
    n = group.order

    if n > PERF_CUTOFF:
        return {"normal_subgroups": [], "total_count": 0, "truncated": True}

    # Get conjugacy classes
    cc_result = compute_conjugacy_classes(group)
    classes: list[list[GroupElement]] = []
    for cls_ids in cc_result["classes"]:
        eles = [group.element_by_id(eid["id"]) for eid in cls_ids]
        classes.append([e for e in eles if e is not None])

    # Separate identity class
    identity_id = group.elements[group.identity_idx].id
    identity_class = None
    other_classes: list[list[GroupElement]] = []
    for cls in classes:
        if any(e.id == identity_id for e in cls):
            identity_class = cls
        else:
            other_classes.append(cls)

    if identity_class is None:
        identity_class = [group.elements[group.identity_idx]]

    k = len(other_classes)
    seen_keys: set[str] = set()
    normal_subs: list[dict] = []

    # Always include {e} and G
    all_ids = frozenset(e.id for e in group.elements)
    id_set_e = frozenset([identity_id])

    for mask in range(1 << k):
        union = set(e.id for e in identity_class)
        for i in range(k):
            if mask & (1 << i):
                for e in other_classes[i]:
                    union.add(e.id)

        key = ",".join(sorted(union))
        if key in seen_keys:
            continue
        seen_keys.add(key)

        if len(union) == 0:
            continue

        # Check if closed under multiplication
        if not _is_subgroup_closed(group, union):
            continue

        is_normal = _is_normal_closure(group, union)
        if not is_normal and union != all_ids and union != id_set_e:
            continue

        e_list = sorted((group.element_by_id(eid) for eid in union if group.element_by_id(eid)),
                        key=lambda e: e.id)
        normal_subs.append({
            "elements": [{"id": e.id, "label": e.label, "value": e.value} for e in e_list],
            "is_normal": True,
            "order": len(e_list),
        })

    normal_subs.sort(key=lambda s: s["order"])

    return {"normal_subgroups": normal_subs, "total_count": len(normal_subs)}


def _is_subgroup_closed(group: Group, ids: set[str]) -> bool:
    """Check if a set of element IDs is closed under multiplication."""
    for i_id in ids:
        i_idx = group._id_to_idx[i_id]
        for j_id in ids:
            j_idx = group._id_to_idx[j_id]
            prod_idx = group._table[i_idx][j_idx]
            if group.elements[prod_idx].id not in ids:
                return False
    return True


# ── Conjugacy Classes ───────────────────────────────────────────────────────

def compute_conjugacy_classes(group: Group) -> dict:
    """Compute conjugacy classes of G."""
    n = group.order

    if n > PERF_CUTOFF:
        # Return each element as its own class
        classes = [[{"id": e.id, "label": e.label, "value": e.value}] for e in group.elements]
        return {"classes": classes, "truncated": True}

    assigned: set[str] = set()
    classes: list[list[dict]] = []

    for a in group.elements:
        if a.id in assigned:
            continue

        conjugates: list[dict] = []
        # For each g in G, compute g * a * g^{-1}
        a_idx = group._id_to_idx[a.id]
        for g in group.elements:
            g_idx = group._id_to_idx[g.id]
            ga = group._table[g_idx][a_idx]
            ginv = group._inverse_map[g_idx]
            conj_idx = group._table[ga][ginv]
            conj_el = group.elements[conj_idx]
            if conj_el.id not in assigned:
                assigned.add(conj_el.id)
                conjugates.append({"id": conj_el.id, "label": conj_el.label, "value": conj_el.value})

        if conjugates:
            classes.append(conjugates)

    return {"classes": classes}


# ── Center ─────────────────────────────────────────────────────────────────

def compute_center(group: Group) -> dict:
    """Compute the center Z(G) = {g in G | gx = xg for all x in G}."""
    n = group.order

    if n > PERF_CUTOFF:
        identity = group.elements[group.identity_idx]
        return {"center": [{"id": identity.id, "label": identity.label, "value": identity.value}]}

    center_els: list[dict] = []
    for a in group.elements:
        a_idx = group._id_to_idx[a.id]
        is_central = True
        for g in group.elements:
            g_idx = group._id_to_idx[g.id]
            # a * g
            ag = group._table[a_idx][g_idx]
            # g * a
            ga = group._table[g_idx][a_idx]
            if ag != ga:
                is_central = False
                break
        if is_central:
            center_els.append({"id": a.id, "label": a.label, "value": a.value})

    return {"center": center_els}


# ── Cosets ─────────────────────────────────────────────────────────────────

def compute_cosets(group: Group, subgroup_ids: list[str]) -> Optional[dict]:
    """Compute left and right cosets for a given subgroup."""
    # Build subgroup element set
    subgroup_set = {sid for sid in subgroup_ids if group.element_by_id(sid)}
    if len(subgroup_set) < 1 or len(subgroup_set) >= group.order:
        return None

    subgroup_elems = [group.element_by_id(sid) for sid in subgroup_ids if group.element_by_id(sid)]
    # Check if it's actually a subgroup
    if not _is_subgroup_closed(group, {e.id for e in subgroup_elems}):
        return None

    # Left cosets: for each g, compute gH
    left_cosets: list[list[dict]] = []
    left_seen: set[str] = set()
    for g in group.elements:
        coset = []
        g_idx = group._id_to_idx[g.id]
        for h in subgroup_elems:
            h_idx = group._id_to_idx[h.id]
            prod_idx = group._table[g_idx][h_idx]
            prod = group.elements[prod_idx]
            coset.append({"id": prod.id, "label": prod.label, "value": prod.value})
        key = ",".join(sorted(c["id"] for c in coset))
        if key not in left_seen:
            left_seen.add(key)
            left_cosets.append(sorted(coset, key=lambda c: c["id"]))

    # Right cosets: for each g, compute Hg
    right_cosets: list[list[dict]] = []
    right_seen: set[str] = set()
    for g in group.elements:
        coset = []
        g_idx = group._id_to_idx[g.id]
        for h in subgroup_elems:
            h_idx = group._id_to_idx[h.id]
            prod_idx = group._table[h_idx][g_idx]
            prod = group.elements[prod_idx]
            coset.append({"id": prod.id, "label": prod.label, "value": prod.value})
        key = ",".join(sorted(c["id"] for c in coset))
        if key not in right_seen:
            right_seen.add(key)
            right_cosets.append(sorted(coset, key=lambda c: c["id"]))

    # Is the subgroup normal?
    is_normal = left_seen == right_seen

    return {
        "left_cosets": left_cosets,
        "right_cosets": right_cosets,
        "is_normal": is_normal,
        "num_cosets": len(left_cosets),
    }


# ── Subgroup Lattice (Hasse Diagram) ────────────────────────────────────────

def compute_subgroup_lattice(group: Group, precomputed_subs: list[dict] | None = None) -> dict:
    """Compute the subgroup lattice (Hasse diagram)."""
    n = group.order

    if n > PERF_CUTOFF:
        return {"nodes": [], "edges": [], "truncated": True}

    if precomputed_subs is not None:
        subgroups = precomputed_subs
    else:
        subs_result = compute_subgroups(group)
        subgroups = subs_result["subgroups"]

    # Build nodes
    nodes: list[dict] = []
    for i, sub in enumerate(subgroups):
        nodes.append({
            "id": i,
            "elements": sub["elements"],
            "order": sub["order"],
            "is_normal": sub["is_normal"],
            "level": 0,  # calculated below
        })

    m = len(nodes)
    if m == 0:
        return {"nodes": [], "edges": []}

    # Containment matrix
    contains: list[list[bool]] = [[False] * m for _ in range(m)]
    for i in range(m):
        ids_i = {e["id"] for e in nodes[i]["elements"]}
        for j in range(m):
            if i == j:
                contains[i][j] = True
            else:
                ids_j = {e["id"] for e in nodes[j]["elements"]}
                contains[i][j] = ids_i.issubset(ids_j)

    # Hasse edges: direct containment (transitive reduction)
    # Sort indices by order for efficient traversal
    order_indices = sorted(range(m), key=lambda idx: nodes[idx]["order"])
    edges: list[dict] = []
    for i in range(m):
        oi = nodes[i]["order"]
        for j in range(m):
            if i == j:
                continue
            if not contains[i][j]:
                continue
            oj = nodes[j]["order"]
            if oi >= oj:
                continue

            # Only check k with order strictly between oi and oj
            direct = True
            for k in order_indices:
                ok = nodes[k]["order"]
                if ok <= oi or ok >= oj or k == i or k == j:
                    continue
                if contains[i][k] and contains[k][j]:
                    direct = False
                    break
            if direct:
                edges.append({"source": i, "target": j})

    # Assign levels: bottom (trivial) to top (full group)
    # Sort by order, then assign levels so smaller subgroups at bottom
    sorted_by_order = sorted(range(m), key=lambda idx: nodes[idx]["order"])
    order_map: dict[int, int] = {}
    for rank, idx in enumerate(sorted_by_order):
        order_map[idx] = rank

    max_level = max(order_map.values()) if order_map else 0
    for i in range(m):
        nodes[i]["level"] = max_level - order_map.get(i, 0)

    return {"nodes": nodes, "edges": edges}


# ── Cayley Edges ────────────────────────────────────────────────────────────

COLOR_PALETTE = [
    "#ff6b6b", "#4ecdc4", "#ffd93d", "#a78bfa", "#f97316", "#06b6d4",
    "#84cc16", "#f43f5e", "#38bdf8", "#a855f7", "#14b8a6", "#eab308",
    "#6366f1", "#ec4899", "#0ea5e9", "#22c55e",
]


def compute_cayley_edges(
    group: Group,
    action_element_ids: list[str],
    multiply_type: str = "right",
) -> dict:
    """Compute Cayley graph edges for given action elements."""
    n = group.order

    # Cap edges for large groups
    max_edges = max(120, n * 3) if n > PERF_CUTOFF else 1_000_000

    # Assign colors to actions
    action_colors: dict[str, str] = {}
    for i, aid in enumerate(action_element_ids):
        action_colors[aid] = COLOR_PALETTE[i % len(COLOR_PALETTE)]

    edges: list[dict] = []
    edge_count = 0

    for i, a in enumerate(group.elements):
        for aid in action_element_ids:
            c = group.element_by_id(aid)
            if c is None:
                continue

            if multiply_type == "right":
                # a * c
                prod_idx = group._table[group._id_to_idx[a.id]][group._id_to_idx[c.id]]
            else:
                # c * a
                prod_idx = group._table[group._id_to_idx[c.id]][group._id_to_idx[a.id]]

            b = group.elements[prod_idx]
            color = action_colors[aid]
            is_self_loop = a.id == b.id

            # Bidirectional detection: if c^{-1} = c (self-inverse) → bidirectional
            c_idx = group._id_to_idx[c.id]
            inv_idx = group._inverse_map[c_idx]
            is_bidirectional = (inv_idx == c_idx) or is_self_loop

            edges.append({
                "from_idx": i,
                "to_idx": prod_idx,
                "from_id": a.id,
                "to_id": b.id,
                "action_element_id": aid,
                "color": color,
                "is_bidirectional": is_bidirectional,
                "is_self_loop": is_self_loop,
            })

            edge_count += 1
            if edge_count >= max_edges:
                break

        if edge_count >= max_edges:
            break

    return {"edges": edges}
