import { describe, it, expect } from 'vitest'
import {
  computeCycleSubgroups,
  computeMaximalCycles,
  forceLayout,
  planarCycleLayout,
} from '../core/algebra/cycleLayouts'
import { createCyclicGroup } from '../core/groups/CyclicGroup'
import { createS3 } from '../core/groups/SymmetricGroup'
import type { GroupElement } from '../core/types'

const el = (id: string): GroupElement => ({ id, label: id, value: [] })

describe('computeCycleSubgroups', () => {
  it('finds the subgroup cycles of C6 (order > 2)', () => {
    const c6 = createCyclicGroup(6)
    const cycles = computeCycleSubgroups(c6)
    expect(cycles.length).toBeGreaterThanOrEqual(1)
    // The cycle generated by e2 has 3 elements, by e1/e5 has 6
    const hasSix = cycles.some(c => c.length === 6)
    const hasThree = cycles.some(c => c.length === 3)
    expect(hasSix).toBe(true)
    expect(hasThree).toBe(true)
  })

  it('excludes 2-element cycles (involutions)', () => {
    const s3 = createS3()
    const cycles = computeCycleSubgroups(s3)
    for (const c of cycles) {
      expect(c.length).toBeGreaterThan(2)
    }
  })
})

describe('computeMaximalCycles', () => {
  it('keeps only cycles not contained in others', () => {
    const c = (ids: string[]) => ({ elements: ids.map(el) })
    const cycles = [c(['a', 'b', 'c']), c(['a', 'b', 'c', 'd']), c(['x', 'y'])]
    const result = computeMaximalCycles(cycles)
    expect(result).toHaveLength(2)
    expect(result.map(r => r.elements.length)).toEqual([4, 2])
  })

  it('keeps equal-size disjoint cycles', () => {
    const c = (ids: string[]) => ({ elements: ids.map(el) })
    const result = computeMaximalCycles([c(['a', 'b']), c(['c', 'd'])])
    expect(result).toHaveLength(2)
  })
})

describe('forceLayout', () => {
  it('returns a position for every element', () => {
    const elements = [el('a'), el('b'), el('c'), el('d')]
    const pos = forceLayout(elements, [
      { source: 'a', target: 'b' },
      { source: 'b', target: 'c' },
    ], 800, 800)
    expect(pos.size).toBe(4)
    for (const e of elements) {
      expect(pos.get(e.id)).toBeDefined()
    }
  })

  it('filters self-loop edges', () => {
    const elements = [el('a'), el('b')]
    const pos = forceLayout(elements, [
      { source: 'a', target: 'a' },
      { source: 'a', target: 'unknown' },
    ], 800, 800)
    expect(pos.size).toBe(2)
  })

  it('honors initial positions', () => {
    const elements = [el('a'), el('b')]
    const initial = new Map([['a', { x: 100, y: 100 }]])
    const pos = forceLayout(elements, [], 800, 800, { initialPositions: initial })
    expect(pos.size).toBe(2)
  })

  it('uses cycle subgroups when provided', () => {
    const elements = [el('a'), el('b'), el('c'), el('d')]
    const pos = forceLayout(elements, [], 800, 800, { cycleSubgroups: [[0, 1, 2]] })
    expect(pos.size).toBe(4)
  })

  it('returns empty map for empty input', () => {
    expect(forceLayout([], [], 800, 800).size).toBe(0)
  })
})

describe('planarCycleLayout', () => {
  it('centers the identity and fills remaining elements on a circle when no cycles', () => {
    const elements = [el('e'), el('a'), el('b'), el('c')]
    const pos = planarCycleLayout(elements, [], 800, 800)
    expect(pos.size).toBe(4)
    expect(pos.get('e')!.x).toBe(400)
    expect(pos.get('e')!.y).toBe(400)
  })

  it('returns empty for empty input', () => {
    expect(planarCycleLayout([], [], 800, 800).size).toBe(0)
  })

  it('lays out shared cycles with identity in the middle', () => {
    const elements = [el('e'), el('a'), el('b'), el('c'), el('d')]
    const pos = planarCycleLayout(elements, [
      { elements: [el('a'), el('b'), el('c')] },
      { elements: [el('c'), el('d'), el('a')] },
    ], 800, 800)
    expect(pos.size).toBe(5)
    expect(pos.get('e')!.x).toBe(400)
  })

  it('handles singleton cycles (one non-identity element)', () => {
    const elements = [el('e'), el('a')]
    const pos = planarCycleLayout(elements, [{ elements: [el('a')] }], 800, 800)
    expect(pos.size).toBe(2)
  })

  it('falls back to a circle when shared elements exceed two', () => {
    const elements = [el('e'), el('a'), el('b'), el('c'), el('d')]
    const pos = planarCycleLayout(elements, [
      { elements: [el('a'), el('b'), el('c')] },
      { elements: [el('a'), el('b'), el('d')] },
      { elements: [el('a'), el('c'), el('d')] },
      { elements: [el('b'), el('c'), el('d')] },
    ], 800, 800)
    expect(pos.size).toBe(5)
  })
})